### ISSUE TITLE
it appears heyoka also has a implicit dependency on zlib but its not on the main page of pre-reqs[BUG]

### ISSUE THREAD

**Issue by jdmairs** [bluescarni/heyoka#155]
**Describe the bug**
When building heyoka from github source via CMake, cmake cannot find the zlib library.  

**To Reproduce**
1. Downloaded llvm 10.  Built using cmake -DLLVM_TARGETS_TO_BUILD=X86
2. Installed llvm.
3. run heyoka cmake ..
4. Error cmake find_package cannot find zlib.

**Expected behavior**
Since I download boost, fmt, spdlog, and llvm I expected the cmake generation build system step to work.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10
 - Installation method: [source]
 - Version: [0.10]

**Additional context**

**Comment by bluescarni** [comment]
Hi @jdmairs thanks for the report.

The dependency on zlib is a workaround due to the fact that (at least some versions of) LLVM ship on Windows with CMake config package files which directly link to the ``z`` library, which typically ends up failing if ``zlib`` is not installed in a standard location. This is an issue with the LLVM build system, which in theory should take care of locating its own dependencies.

This issue was present at least in LLVM10 but perhaps it was solved eventually. Could you try commenting out lines 309 to 317 in the main CMakeLists.txt?

**Comment by jdmairs** [comment]
Hi thanks for the quick reply.

I did comment out the lines and successfully generated the build files;
however VS2017 15.9.24 is having alot of problems.  I wrote a separate
ticket for that.

**Comment by bluescarni** [comment]
Thanks for testing out. I'll try to comment out the workaround in the build system and see how it goes then.

**Comment by bluescarni** [comment]
@jdmairs as an additional word of warning, there might be a temporary issue if you use ``fmt`` version 8 - this stems from incompatibilities between ``fmt`` and ``spdlog`` that should be shortly resolved upstream.

In the meantime, I'd advise to stick with ``fmt`` 7.

**Comment by bluescarni** [comment]
@jdmairs I have removed the ``zlib`` bits from the CMakeLists.txt in the master branch. Note that heyoka still has an indirect dependency on ``zlib`` (in the sense that LLVM depends on it), but at least now heyoka's build system is not trying to locate ``zlib`` any more.

Thanks for the report, closing for now.
